#pragma once

#include "VSAccessFlagsDef.h"

namespace VulkanSimplified
{
	enum AccessFlagBits : AccessFlags
	{
		ACCESS_NONE = 0,
		ACCESS_INDIRECT_COMMAND_READ = 0x1,
		ACCESS_INDEX_READ = 0x2,
		ACCESS_VERTEX_ATTRIBUTE_READ = 0x4,
		ACCESS_UNIFORM_READ = 0x8,
		ACCESS_INPUT_ATTACHMENT_READ = 0x10,
		ACCESS_SHADER_READ = 0x20,
		ACCESS_SHADER_WRITE = 0x40,
		ACCESS_COLOR_ATTACHMENT_READ = 0x80,
		ACCESS_COLOR_ATTACHMENT_WRITE = 0x100,
		ACCESS_DEPTH_STENCIL_READ = 0x200,
		ACCESS_DEPTH_STENCIL_WRITE = 0x400,
		ACCESS_TRANSFER_READ = 0x800,
		ACCESS_TRANSFER_WRITE = 0x1000,
		ACCESS_HOST_READ = 0x2000,
		ACCESS_HOST_WRITE = 0x4000,
		ACCESS_MEMORY_READ = 0x8000,
		ACCESS_MEMORY_WRITE = 0x10000,
	};
}