#pragma once

#include "VSSurfaceTransformFlagsDef.h"

namespace VulkanSimplified
{
	enum SurfaceTransformFlagBits : SurfaceTransformFlags
	{
		SURFACE_TRASFORM_IDENTITY = 0x1,
		SURFACE_TRASFORM_ROTATE_90 = 0x2,
		SURFACE_TRASFORM_ROTATE_180 = 0x4,
		SURFACE_TRASFORM_ROTATE_270 = 0x8,
		SURFACE_TRASFORM_HORIZONTAL_MIRROR = 0x10,
		SURFACE_TRASFORM_HORIZONTAL_MIRROR_ROTATE_90 = 0x20,
		SURFACE_TRASFORM_HORIZONTAL_MIRROR_ROTATE_180 = 0x40,
		SURFACE_TRASFORM_HORIZONTAL_MIRROR_ROTATE_270 = 0x80,
	};
}