#include "VSCommonDNIpch.h"
#include "VSAccessFlagsInternal.h"

namespace VulkanSimplified
{
	VkAccessFlags TranslataAccessFlags(AccessFlags accessFlags)
	{
		VkAccessFlags ret = 0;

		if (accessFlags == AccessFlagBits::ACCESS_NONE)
			return ret;

		if ((accessFlags & ACCESS_INDIRECT_COMMAND_READ) == ACCESS_INDIRECT_COMMAND_READ)
			ret |= VK_ACCESS_INDIRECT_COMMAND_READ_BIT;

		if ((accessFlags & ACCESS_INDEX_READ) == ACCESS_INDEX_READ)
			ret |= VK_ACCESS_INDEX_READ_BIT;

		if ((accessFlags & ACCESS_VERTEX_ATTRIBUTE_READ) == ACCESS_VERTEX_ATTRIBUTE_READ)
			ret |= VK_ACCESS_VERTEX_ATTRIBUTE_READ_BIT;

		if ((accessFlags & ACCESS_UNIFORM_READ) == ACCESS_UNIFORM_READ)
			ret |= VK_ACCESS_UNIFORM_READ_BIT;

		if ((accessFlags & ACCESS_INPUT_ATTACHMENT_READ) == ACCESS_INPUT_ATTACHMENT_READ)
			ret |= VK_ACCESS_INPUT_ATTACHMENT_READ_BIT;

		if ((accessFlags & ACCESS_SHADER_READ) == ACCESS_SHADER_READ)
			ret |= VK_ACCESS_SHADER_READ_BIT;

		if ((accessFlags & ACCESS_SHADER_WRITE) == ACCESS_SHADER_WRITE)
			ret |= VK_ACCESS_SHADER_WRITE_BIT;

		if ((accessFlags & ACCESS_COLOR_ATTACHMENT_READ) == ACCESS_COLOR_ATTACHMENT_READ)
			ret |= VK_ACCESS_COLOR_ATTACHMENT_READ_BIT;

		if ((accessFlags & ACCESS_COLOR_ATTACHMENT_WRITE) == ACCESS_COLOR_ATTACHMENT_WRITE)
			ret |= VK_ACCESS_COLOR_ATTACHMENT_WRITE_BIT;

		if ((accessFlags & ACCESS_DEPTH_STENCIL_READ) == ACCESS_DEPTH_STENCIL_READ)
			ret |= VK_ACCESS_DEPTH_STENCIL_ATTACHMENT_READ_BIT;

		if ((accessFlags & ACCESS_DEPTH_STENCIL_WRITE) == ACCESS_DEPTH_STENCIL_WRITE)
			ret |= VK_ACCESS_COLOR_ATTACHMENT_WRITE_BIT;

		if ((accessFlags & ACCESS_TRANSFER_READ) == ACCESS_TRANSFER_READ)
			ret |= VK_ACCESS_TRANSFER_READ_BIT;

		if ((accessFlags & ACCESS_TRANSFER_WRITE) == ACCESS_TRANSFER_WRITE)
			ret |= VK_ACCESS_TRANSFER_WRITE_BIT;

		if ((accessFlags & ACCESS_HOST_READ) == ACCESS_HOST_READ)
			ret |= VK_ACCESS_HOST_READ_BIT;

		if ((accessFlags & ACCESS_HOST_WRITE) == ACCESS_HOST_WRITE)
			ret |= VK_ACCESS_HOST_WRITE_BIT;

		if ((accessFlags & ACCESS_MEMORY_READ) == ACCESS_MEMORY_READ)
			ret |= VK_ACCESS_MEMORY_READ_BIT;

		if ((accessFlags & ACCESS_MEMORY_WRITE) == ACCESS_MEMORY_WRITE)
			ret |= VK_ACCESS_MEMORY_WRITE_BIT;

		return ret;
	}
}